### ISSUE TITLE
valve.rc fail

### ISSUE THREAD

**Issue by radiumx3** [dgibbs64/linuxgsm#748] opened 2016-03-08 00:45 UTC
Redirecting stderr to '/home/csgoserver/Steam/logs/stderr.txt'
[  0%] Checking for available updates...
[----] Verifying installation...
Steam Console Client (c) Valve Corporation
-- type 'quit' to exit --
Loading Steam API...Created shared memory when not owner SteamController_Shared_mem
OK.

Connecting anonymously to Steam Public...Logged in OK
Waiting for license info...OK
Success! App '740' already up to date.
[ FAIL ] Update csgo-server: Applying valve.rc fix: Counter Strike: Global Offensive
[  OK  ] Update csgo-server: Applying workshop map fix: Counter Strike: Global Offensive
[ FAIL ] Starting csgo-server: Applying valve.rc fix: Counter Strike: Global Offensive
[  OK  ] Starting csgo-server: http://skins.zone Dedicated server

Is that error revelant ?

**Comment by UltimateByte** [comment] 2016-03-08 19:27
@dgibbs64 May know more about that ?

**Comment by UltimateByte** [comment] 2016-06-13 22:22
Did you solved this ?

**Comment by radiumx3** [comment] 2016-06-29 17:39
Nope... still waiting for an update:/

**Comment by UltimateByte** [comment] 2016-06-30 02:11
./csgoserver details ?

**Comment by UltimateByte** [comment] 2016-06-30 02:12
Doesn't the server work ?
./csgoserver debug
and ls -al /home/csgoserver

**Comment by dgibbs64** [comment] 2016-07-12 22:32
The "error" is just LGSM applying a fix for the server and does not tell me what the issue is.
Please provide all relevant info
http://steamcommunity.com/groups/linuxgsm/discussions/0/458604254471755996/

**Comment by dgibbs64** [comment] 2016-08-07 22:20
closing as no update

**Closed** 2016-08-07 22:20 UTC
