### ISSUE TITLE
Tickrate?

### ISSUE THREAD

**Issue by xFirez** [dgibbs64/linuxgsm#961] opened 2016-08-01 03:07 UTC
How does one set tickrate?

**Comment by ncronin** [comment] 2016-08-01 07:35
For CS:GO it's already included in the script (csgoserver) to add to another game such as TF2 or CS:S simple edit the tfserver/csserver file with the following:

Find `maxplayers="##"` and below add `tickrate="##"` where ## is the number of players/tickrate you desire.

Then find:
`parms="-game cstrike -strictportbind -ip ${ip} -port ${port} +clientport ${clientport} +tv_port ${sourcetvport} +map ${defaultmap} +sv_setsteamaccount ${gslt} +servercfgfile ${servercfg} -maxplayers ${maxplayers}"`

and add: ` -tickrate ${tickrate}` after `${gslt} +servercfgfile`.

I'm currently using this method on all of my TF2/CS:S servers and it seems to work fine.

**Comment by UltimateByte** [comment] 2016-08-01 14:43
@ncronin Perfect answer, but no need to bother writing it, it's in the wiki. :p 
https://github.com/dgibbs64/linuxgsm/wiki/Start-Parms

Before I close this, @ncronin , so you confirm the -tickrate argument is still working for TF2 and CS:S ?
Because we might add this argument into the default script, which would be more simple. :)

**Comment by ncronin** [comment] 2016-08-02 11:06
Yes, I can confirm.

**Comment by UltimateByte** [comment] 2016-08-02 12:32
@ncronin By any means, would you know the default tickrate for those games ?

**Comment by marvinl97** [comment] 2016-08-03 17:43
> It is not possible to change tickrate on CSS, DoD S TF2, L4D and L4D2 because changing tickrate causes server timing issues. The tickrate is set to 66 in CSS, DoD S and TF2, and 30 in L4D and L4D2.

Source: https://developer.valvesoftware.com/wiki/Source_Multiplayer_Networking

I can't get the rickrate parameter working for CS:S.. So I can't confirm it. Maybe I'm doing something wrong.

**Comment by k0st1an** [comment] 2016-08-03 19:04
@marvinl97 +1

**Comment by UltimateByte** [comment] 2016-08-04 04:13
Well... That's how it was in my memories and why it wasn't in LGSM in the first place. Thought it had changed. according to ncronin.
What's your method for testing the actual tickrate ?

**Comment by ncronin** [comment] 2016-08-04 04:21
My bad. I guess either something was changed or because we have it set in other configurations? IIRC you were able to set it via the start-up line. I will conduct some more tests and report back.

**Comment by jach11** [comment] 2016-08-04 17:01
The tickrate param for CS:S and TF2 was deprecated a while ago. You cannot change it without running a mod, even then it's not worth it. "Removed -tickrate command line option and defaulted tick rate to 66 rather than 33." http://store.steampowered.com/news/3976/

**Comment by UltimateByte** [comment] 2016-08-04 23:30
Well, it's too bad.
I think we can close this now.

**Closed by UltimateByte** 2016-08-04 23:30 UTC
Labels: question
