### ISSUE TITLE
TS3 Update enda in a loop

### ISSUE THREAD

**Issue by gOOvER** [dgibbs64/linuxgsm#680] opened 2016-02-06 07:59 UTC
After latest Fixes TS3 Update ends in a loop

ts3@v37360:~$ ./ts3server update
[  OK  ] Update ts3-server: Checking for update: teamspeak.com

Update available:
        Current build: 3.0.11.4
        Available build: 3.0.12

Applying update...
[  OK  ] Update ts3-server: Updating Teamspeak 3 Server
downloading teamspeak3-server_linux_amd64-3.0.12.tar.bz2...OK
extracting teamspeak3-server_linux_amd64-3.0.12.tar.bz2...OK
copying to /home/ts3/serverfiles...OK
[  OK  ] Update ts3-server: Checking for update: teamspeak.com

Update available:
        Current build: 3.0.11.4
        Available build: 3.0.12

Applying update...
[  OK  ] Update ts3-server: Updating Teamspeak 3 Server
downloading teamspeak3-server_linux_amd64-3.0.12.tar.bz2...OK
extracting teamspeak3-server_linux_amd64-3.0.12.tar.bz2...OK
copying to /home/ts3/serverfiles...OK
[ .... ] Update ts3-server: Checking for update: teamspeak.com

....  and so on,....

**Comment by dgibbs64** [comment] 2016-02-06 08:21
Firstly ./ts3server update-functions then see how it goes

**Comment by dgibbs64** [comment] 2016-02-06 08:33
I just tested without issue. 
./ts3server update-functions
and test again please. It shoudl restart your server automatically and not loop

**Comment by gOOvER** [comment] 2016-02-06 08:34
update-functions is the first thing i do,  after new commits for ts3 are aviable. :) 

normally i fo not use it.  i remove the whole functions Dir :)

**Comment by gOOvER** [comment] 2016-02-06 08:49
ts3@v37360:~$ ./ts3server update-functions
    loading update_functions.sh...OK
[ .... ] Updating functions
removed '/home/ts3/functions/check.sh'
removed '/home/ts3/functions/check_config.sh'
removed '/home/ts3/functions/check_deps.sh'
removed '/home/ts3/functions/check_ip.sh'
removed '/home/ts3/functions/check_logs.sh'
removed '/home/ts3/functions/check_root.sh'
removed '/home/ts3/functions/check_systemdir.sh'
removed '/home/ts3/functions/check_tmux.sh'
removed '/home/ts3/functions/command_start.sh'
removed '/home/ts3/functions/command_stop.sh'
removed '/home/ts3/functions/core_functions.sh'
removed '/home/ts3/functions/core_getopt.sh'
removed '/home/ts3/functions/core_messages.sh'
removed '/home/ts3/functions/fn_functions'
removed '/home/ts3/functions/fn_getopt'
removed '/home/ts3/functions/info_config.sh'
removed '/home/ts3/functions/info_distro.sh'
removed '/home/ts3/functions/info_ts3status.sh'
removed '/home/ts3/functions/update_check.sh'
removed '/home/ts3/functions/update_dl.sh'
removed '/home/ts3/functions/update_functions.sh'
[  OK  ] Updating functions
ts3@v37360:~$ ./ts3server update
    loading fn_functions...OK
    loading core_functions.sh...OK
    loading core_messages.sh...OK
    loading fn_getopt...OK
    loading core_getopt.sh...OK
    loading update_check.sh...OK
    loading check.sh...OK
    loading check_root.sh...OK
    loading check_systemdir.sh...OK
    loading check_logs.sh...OK
[ .... ] Update ts3-server: Checking for update: teamspeak.com    loading info_distro.sh...OK
[  OK  ] Update ts3-server: Checking for update: teamspeak.com

Update available:
        Current build: 3.0.11.4
        Available build: 3.0.12


Applying update...
    loading info_ts3status.sh...OK
    loading update_dl.sh...OK
    loading info_config.sh...OK
[  OK  ] Update ts3-server: Updating Teamspeak 3 Server
downloading teamspeak3-server_linux_amd64-3.0.12.tar.bz2...OK
extracting teamspeak3-server_linux_amd64-3.0.12.tar.bz2...OK
copying to /home/ts3/serverfiles...OK
    loading command_start.sh...OK
    loading check_deps.sh...OK
    loading check_ip.sh...OK
    loading check_tmux.sh...OK
    loading check_config.sh...OK
[  OK  ] Update ts3-server: Checking for update: teamspeak.com

Update available:
        Current build: 3.0.11.4
        Available build: 3.0.12


Applying update...
[  OK  ] Update ts3-server: Updating Teamspeak 3 Server
downloading teamspeak3-server_linux_amd64-3.0.12.tar.bz2...OK
extracting teamspeak3-server_linux_amd64-3.0.12.tar.bz2...OK
copying to /home/ts3/serverfiles...OK
[  OK  ] Update ts3-server: Checking for update: teamspeak.com

Update available:
        Current build: 3.0.11.4
        Available build: 3.0.12


Applying update...
[  OK  ] Update ts3-server: Updating Teamspeak 3 Server
downloading teamspeak3-server_linux_amd64-3.0.12.tar.bz2...OK
extracting teamspeak3-server_linux_amd64-3.0.12.tar.bz2...OK
copying to /home/ts3/serverfiles...OK
[  OK  ] Update ts3-server: Checking for update: teamspeak.com

Update available:
        Current build: 3.0.11.4
        Available build: 3.0.12


Applying update...
[ .... ] Update ts3-server: Updating Teamspeak 3 Server^C
ts3@v37360:~$

**Comment by gOOvER** [comment] 2016-02-06 09:09
Maybe it helps.  I have 2 0Byte tmp files in log:

ts3@v37360:~/log/script$ ls -a
.   .ts3-server-cp-error.tmp   ts3-server-script-06-01-2016-14-12-24.log
..  .ts3-server-tar-error.tmp  ts3-server-script.log
ts3@v37360:~/log/script$

**Comment by dgibbs64** [comment] 2016-02-06 09:19
hmmm. Not sure about this. I will have a play around see if I can figure it out

**Comment by dgibbs64** [comment] 2016-02-06 09:35
./ts3server dev-debug and run the updater again. it will create a log in the main directory called dev-debug.log please send me that, I reccomend using pastebin

**Comment by UltimateByte** [comment] 2016-02-06 11:32
Hi,

If the bug isn't occuring anymore for you : 
What distro are you using, and is "updateonstart" on ?
Was the server on or off when you were running the update command ?
May help looking at the right things.

**Comment by UltimateByte** [comment] 2016-02-06 11:41
@dgibbs64 The problem could be related on how it detects the current version.

After removing all logfiles : 

```
serverdev@lrob:~/ts3server$ ./ts3server update
[ FAIL ] Update ts3-server: Checking for update: teamspeak.com: No logs with server version found
[ INFO ] Update ts3-server: Checking for update: teamspeak.com: Forcing server restart
[ FAIL ] Stopping ts3-server: Teamspeak 3 Server is already stopped
    fetching functions/command_start.sh...OK
[ FAIL ] Update ts3-server: Checking for update: teamspeak.com: No logs with server version found
[ INFO ] Update ts3-server: Checking for update: teamspeak.com: Forcing server restart
[ FAIL ] Stopping ts3-server: Teamspeak 3 Server is already stopped
[ .... ] Update ts3-server: Checking for update: teamspeak.com^C
```

**Comment by UltimateByte** [comment] 2016-02-06 12:00
I've also been able to reproduce the users's bug, virtually changing the version of the ts in the logs.

In my case, it only occured with updateonstart="on" because start function seems to check for updates before starting the server, so logfiles with the new version aren't created yet. My previous bug is also due to that same thing.


So @gOOvER : Is your updateonstart="on" ? I guess it is. Just turn it off, easy fast fix.

Concerning us, we will fix that soon.

**Comment by UltimateByte** [comment] 2016-02-06 12:22
@dgibbs64 Easy fix : Add a variable when checking for update, which will be used to bypass updateonstart update.

**Comment by dgibbs64** [comment] 2016-02-06 12:32
No wonder I couldn't spot the issue. I can resolve this. Will sort it out later :-)

**Comment by gOOvER** [comment] 2016-02-06 12:38
Yes,  autoupdate is on

**Comment by gOOvER** [comment] 2016-02-06 14:02
it works with autoupdate="off"  thanks for the info :)

**Comment by dgibbs64** [comment] 2016-02-06 18:18
Should be fixed now. Please test and let me know.
https://github.com/dgibbs64/linuxgsm/commit/e05a42daae1ae0b4af1fe351a7224b061bac4918

**Comment by UltimateByte** [comment] 2016-02-06 19:03
Tested : Perfect :)

**Closed** 2016-02-06 21:03 UTC
Labels: bug
