### ISSUE TITLE
CS:GO (any) implement a force-start command?

### ISSUE THREAD

**Issue by iNilo** [dgibbs64/linuxgsm#692] opened 2016-02-11 16:37 UTC
We are hosting a dedi with OVH and they are having routing issues.
The steam CMD is not responding and its preventing us from launching the srcds servers.

Would it be possible to implement a "force-start" that just fires off the srcds without checking for updates?

`[ FAIL ] Update csgo-server: Checking for update: SteamCMD: Not returning version info`

**Comment by jaredballou** [comment] 2016-02-11 21:41
We really ought to just handle this sort of error better inside the start command. Something like, if steamcmd doesn't return a result we notify and continue?

**Comment by UltimateByte** [comment] 2016-02-11 22:44
I see that what is failing is the update function, not the start. As far as i know, the start function doesn't check for SteamCMD updates. 
So, if you can't update SteamCMD, chances are you can't update csgoserver neither. I think it's the point of how this function work : if SteamCMD isn't working as intended, don't try anything else.
I wouldn't take too much risks to put this as "wontfix" right away.

You should focus on your issue : 
What kind of routing issues are you experiencing ?
Did you make some tracert ? (can be useful even to tell OVH where the shit happens so they can fix it). Or at least simple pings, just to see what happens ?

Not sure if that kind of issue can be packages related, would be great to mention your distro and to double check dependencies.

**Comment by iNilo** [comment] 2016-02-11 22:54
The issue is not the problem.

OVH has a BGP leak breaking most of their network. (this resulted steamcmd failing)

The issue here is that.

`./csgoserver start`

was not starting the server, which is why _force-start_ should start the server not caring if steamcmd failed.

**Comment by dgibbs64** [comment] 2016-02-11 23:07
Is updatonstart enabled? Start does not check for updates unless updatonstart is enabled

**Comment by iNilo** [comment] 2016-02-11 23:08
`updateonstart="yes"`

Human error found. 

:+1: 

You may close this if it pleases you ;)

**Comment by UltimateByte** [comment] 2016-02-11 23:15
"As far as i know, the start function doesn't check for SteamCMD updates."
I should have added "unless updateonstart is on" :p 

Well, problem solved !

**Closed by UltimateByte** 2016-02-11 23:15 UTC
Labels: non-script issue, question
