### ISSUE TITLE
Problem with Hurtworld script

### ISSUE THREAD

**Issue by rogerhnn** [dgibbs64/linuxgsm#816] opened 2016-05-16 11:32 UTC
Hello, after setting up a hurtworld server using the game script I have this problem:
Set current directory to /home/hurtworld/serverfiles
Found path: /home/hurtworld/serverfiles/Hurtworld.x86

The only thing I changed in the script was the ip, server name and added my steam id to become admin.

Can anyone help me? Thanks

**Comment by UltimateByte** [comment] 2016-05-16 11:56
Hi,
I'm sorry, i don't get what the issue is. Could you make a screenshot or something ?

**Comment by rogerhnn** [comment] 2016-05-16 12:01
Sure, you can check it here: http://i.imgur.com/XefICdv.png

What I did: Started the server and then console:

./hwserver start
./hwserver console

Then I got this message, and I followed everything on the how to setup page.

**Comment by UltimateByte** [comment] 2016-05-16 12:03
The console won't display anything else. This isn't an issue, this is the normal behavior of a Hurtworld server. If you think it sucks, blame Hurtworld team or Unity Engine, or both. :o))

**Comment by rogerhnn** [comment] 2016-05-16 12:09
I know, what I am saying is that the server doesnt start, it give me that message:
Set current directory to /home/hurtworld/serverfiles
Found path: /home/hurtworld/serverfiles/Hurtworld.x86
and then it shuts down.
Like if the directory in the start script is wrong.

**Comment by UltimateByte** [comment] 2016-05-16 12:17
> what I am saying is that the server doesnt start

You didn't say that at any point.
As you're able to see the console, it seems like the server is starting.

If you exit the console with` ctrl + c` (instead of `ctrl + b, d`), that's why the server shutdowns. `ctrl + c` will terminate the process, while `ctrl +b, d` will let it run in background.

`./hwserver start`
Wait a few seconds
then `./hwserver monitor`
-> output ?

Also, when adding you as an admin, make sure you follow the right syntax : 
`admins="addadmin 012345678901234567"`

**Comment by rogerhnn** [comment] 2016-05-16 12:27
I use the ctrl+b, d to exit the console.
The addadmin is correct.

This is my output:

`[hwserver@ubuntu-1gb-nyc3-01 ~]$ ./hwserver start
[  OK  ] Starting hurtworld-server: BR Survival x5 |TP|Home|Shop
[hwserver@ubuntu-1gb-nyc3-01 ~]$ ./hwserver monitor
    fetching functions/command_monitor.sh...OK
[  OK  ] Monitor hurtworld-server: Checking session: OK
    fetching functions/monitor_gsquery.sh...OK
[ .... ] Monitor hurtworld-server: Querying port: 104.131.107.91:12881 : QUERYIN           [ FAIL ] Monitor hurtworld-server: Querying port: 104.131.107.91:12881 : ERROR:            Unable to receive
[ FAIL ] Monitor hurtworld-server: Querying port: 104.131.107.91:12881 : ERROR: Unable to receive
[ FAIL ] Stopping hurtworld-server: BR Survival x5 |TP|Home|Shop is already stopped
[  OK  ] Starting hurtworld-server: BR Survival x5 |TP|Home|Shop
[hwserver@ubuntu-1gb-nyc3-01 ~]$ ./hwserver monitor
[  OK  ] Monitor hurtworld-server: Checking session: OK
[  OK  ] Monitor hurtworld-server: Querying port: 104.131.107.91:12881 : OK
[hwserver@ubuntu-1gb-nyc3-01 ~]$ ./hwserver monitor
[  OK  ] Monitor hurtworld-server: Checking session: OK
[  OK  ] Monitor hurtworld-server: Querying port: 104.131.107.91:12881 : OK
[hwserver@ubuntu-1gb-nyc3-01 ~]$
`
Strange is that I can't connect, I got a no response from server message.

**Comment by UltimateByte** [comment] 2016-05-16 12:37
OK, so your first "monitor" attempt failed, but the second one is fine.
If the monitor says OK, it means your server accept querying, and supposedly connections from local.

No response could be a firewall issue,either on your OS, or a hardware firewall to set from your server provider. Also make sure that for some reason, you don't have several hurtworld processes started. (use the "top" command or webmin to check).

**Comment by rogerhnn** [comment] 2016-05-16 12:41
I checked now it says firewall is not running, and only one process is running.
I have to run firewall to enable the tcp/udp connections so?

**Comment by UltimateByte** [comment] 2016-05-16 12:51
Nope. If `iptables -L` shows you the default policy is to accept connections, you have nothing to do.
However, some servers like the "game" series from OVH have a firewal that you have to manage from your OVH panel. I'd search for that.

You can also use the `netstat -atunp | grep Hurtworld` command to check that your Hurtworld server is listening correctly for connections. If the monitor function tells you it's OK, then everything should be normal there.

After that, i'll be a bit short on clues if you can't manage to get it working.

**Comment by rogerhnn** [comment] 2016-05-16 13:32
Okay, so far so good. The server appears on the server list now.
But for some strange reason I can't connect to it.

I started the firewalld service, and added the ports 12871 and 12881 to the list. Both tcp and udp.

Tried the command you said: netstat -atunp it outputs this:

```
[hwserver@ubuntu-1gb-nyc3-01 ~]$ netstat -atunp | grep Hurtworld
(Not all processes could be identified, non-owned process info
 will not be shown, you would have to be root to see it all.)
udp        0      0 0.0.0.0:3565            0.0.0.0:*                           4427/./Hurtworld.x8
udp        0      0 0.0.0.0:12881           0.0.0.0:*                           4427/./Hurtworld.x8

```
I am using DigitalOcean with centos 7.2 to deploy a test server.

**Comment by UltimateByte** [comment] 2016-05-16 13:35
Why put a firewall when you're diagnosing stuff ? -_-

**Comment by rogerhnn** [comment] 2016-05-16 13:38
Because before the udp and tcp ports were closed, I activated the firewall service to enable them.

Why its so hard to get it working under linux -_-

**Comment by UltimateByte** [comment] 2016-05-16 13:40
No firewall doesn't mean the ports are closed. It means there is no restriction.
If your firewall policy was to deny all connections, of course it couldn't work.

Here is a properly disabled firewall output

```
root@game:~# iptables -L
Chain INPUT (policy ACCEPT)
target     prot opt source               destination

Chain FORWARD (policy ACCEPT)
target     prot opt source               destination

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination
```

**Comment by rogerhnn** [comment] 2016-05-16 13:52
I disabled the firewall and it outputs:
`[root@ubuntu-1gb-nyc3-01 ~]# iptables -L
Chain INPUT (policy ACCEPT)
target     prot opt source               destination

Chain FORWARD (policy ACCEPT)
target     prot opt source               destination

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination
`

**Comment by UltimateByte** [comment] 2016-05-16 14:16
And you still can't connect ? What is the exact message ?

You didn't answer about that : Does your server have another kind of firewall ? Like a hardware firewall, that you would setup within your server provider's panel ?

**Comment by rogerhnn** [comment] 2016-05-16 14:19
The only message it gives is that I can't connect.

There's no other firewall, not from the panel itself.

**Comment by UltimateByte** [comment] 2016-05-16 14:23
What is the exact message ?

**Comment by rogerhnn** [comment] 2016-05-16 14:24
http://i.imgur.com/pkO3tpu.png

This is what shows, and the message is "connection failed"
The server appears on the list

**Comment by UltimateByte** [comment] 2016-05-16 14:27
Can you connect to other servers ? (make sure it's not a client issue)
Are both your client and server up to date ?
./hwserver validate

**Comment by UltimateByte** [comment] 2016-05-16 14:42
Boy, i noticed you're lacking a port listening.

Compare to my output : 

```
ultimatebyte@game:~/hwtest$ netstat -atunp | grep Hurtworld
udp        0      0 0.0.0.0:12871           0.0.0.0:*                           28772/Hurtworld.x86
udp        0      0 0.0.0.0:12881           0.0.0.0:*                           28772/Hurtworld.x86
udp        0      0 0.0.0.0:3565            0.0.0.0:*                           28772/Hurtworld.x86
```

**Comment by rogerhnn** [comment] 2016-05-16 14:43
Yeah I can connect to others. I have 1 server up using windows, but the problem is linux.
I validated the files, started it again and same...

It may be something with a port???

**Comment by UltimateByte** [comment] 2016-05-16 14:43
See my upper message.

What's your distro ?

**Comment by rogerhnn** [comment] 2016-05-16 14:44
I am using Centos 7.2

**Comment by UltimateByte** [comment] 2016-05-16 15:01
Any reason for using CentOS ?
I'd recommend Debian 8 or Ubuntu 14+. 64 bits.

BTW, your query port is listening and responds, that's why monitor says it's ok, and that's why you're listed into the server list. But for some reason, your game port isn't listening. Don't mess with the firewall again, if the process doesn't even listen correctly, you can open whatever you want it won't help.

`./hwserver details`
Output of "Command-line Parameters" section ?

**Comment by rogerhnn** [comment] 2016-05-16 15:26
Okay, I will destroy this vps and create another with Ubuntu 14 so..

The output of server details:
```
Distro Details
========================================================================================================================================================================================================
Distro:   CentOS Linux release 7.2.1511 (Core)
Arch:   x86_64
Kernel:   3.10.0-327.10.1.el7.x86_64
Hostname:   ubuntu-1gb-nyc3-01
tmux:   tmux 1.8
GLIBC:   2.17

Performance
========================================================================================================================================================================================================
Uptime:   0d, 3h, 27m
Avg Load:   0.28, 0.09, 0.06

Mem:   total    used   free
Physical:   993M   393M   66M
Swap:   0B   0B     0B

Storage
========================================================================================================================================================================================================
Filesystem:   /dev/vda1
Total:   30G
Used:   2.8G
Available:   26G
Serverfiles:   1.4G

Hurtworld Server Details
========================================================================================================================================================================================================
Server name:   BR Survival x5 |TP|Home|Shop
Server IP:   104.131.107.91:12871
Slots:   50
Game world:   diemensland
Status:   ONLINE

hwserver Script Details
========================================================================================================================================================================================================
Service name:   hurtworld-server
hwserver version:   271215
User:   hwserver
GLIBC required:   2.15
Email notification:   off
Location:   /home/hwserver

Backups
========================================================================================================================================================================================================
No Backups created

Command-line Parameters
========================================================================================================================================================================================================
./Hurtworld.x86 -batchmode -nographics -exec "host 12871 diemensland ;queryport 12881;maxplayers 50;servername BR Survival x5 |TP|Home|Shop;creativemode 0;76561198024356708" -logfile "gamelog.txt"

Ports
========================================================================================================================================================================================================
Change ports by editing the parameters in
hwserver script

Useful port diagnostic command:
netstat -atunp | grep Hurtworld

DESCRIPTION  DIRECTION  PORT   PROTOCOL
> Game/RCON  INBOUND    12871  udp
> Query      INBOUND    12881  udp


Status: ONLINE

```

**Comment by UltimateByte** [comment] 2016-05-16 15:41
In your hwserver
You have map="diemensland" don't you ?
Try to remove "diemensland"
so that you have map=""
And restart hwserver.

**Comment by UltimateByte** [comment] 2016-05-16 15:43
More importantly, your admin syntax is wrong.
What did i tell you in my first posts ?

> Also, when adding yourself as an admin, make sure you follow the right syntax : 
admins="addadmin 012345678901234567"

What did you do ?
`admins="76561198024356708"` >>>>>> WRONG WRONG WRONG
Can't you actually read ?

>>>>> admins="addadmin 76561198024356708"

**Comment by rogerhnn** [comment] 2016-05-16 15:48
I corrected that already. Sorry :(

Here's the corrected:

```
Distro Details
========================================================================================================================================================================================================
Distro:   CentOS Linux release 7.2.1511 (Core)
Arch:   x86_64
Kernel:   3.10.0-327.10.1.el7.x86_64
Hostname:   ubuntu-1gb-nyc3-01
tmux:   tmux 1.8
GLIBC:   2.17

Performance
========================================================================================================================================================================================================
Uptime:   0d, 3h, 48m
Avg Load:   0.34, 0.52, 0.31

Mem:   total    used   free
Physical:   993M   388M   70M
Swap:   0B   0B     0B

Storage
========================================================================================================================================================================================================
Filesystem:   /dev/vda1
Total:   30G
Used:   2.8G
Available:   26G
Serverfiles:   1.4G

Hurtworld Server Details
========================================================================================================================================================================================================
Server name:   BR Survival x5 |TP|Home|Shop
Server IP:   104.131.107.91:12871
Slots:   50
Game world:   NO MAP SET
Status:   ONLINE

hwserver Script Details
========================================================================================================================================================================================================
Service name:   hurtworld-server
hwserver version:   271215
User:   hwserver
GLIBC required:   2.15
Email notification:   off
Location:   /home/hwserver

Backups
========================================================================================================================================================================================================
No Backups created

Command-line Parameters
========================================================================================================================================================================================================
./Hurtworld.x86 -batchmode -nographics -exec "host 12871  ;queryport 12881;maxplayers 50;servername BR Survival x5 |TP|Home|Shop;creativemode 0;addadmin 76561198024356708" -logfile "gamelog.txt"

Ports
========================================================================================================================================================================================================
Change ports by editing the parameters in
hwserver script

Useful port diagnostic command:
netstat -atunp | grep Hurtworld

DESCRIPTION  DIRECTION  PORT   PROTOCOL
> Game/RCON  INBOUND    12871  udp
> Query      INBOUND    12881  udp


Status: ONLINE

```

The strange thing is that the game tries to connect to that ip:12881 and not 12871

**Comment by UltimateByte** [comment] 2016-05-16 15:51
Now it looks better.
`./hwserver restart`
Then wait 30s
Then : `netstat -atunp | grep Hurtworld`
Output  ?

**Comment by rogerhnn** [comment] 2016-05-16 16:12
Strange, now it shows this when I use that command:

[hwserver@ubuntu-1gb-nyc3-01 ~]$ netstat -atunp | grep Hurtworld
(No info could be read for "-p": geteuid()=1000 but you should be root.)

**Comment by rogerhnn** [comment] 2016-05-16 16:14
Now it shows this:

```
[hwserver@ubuntu-1gb-nyc3-01 ~]$ netstat -atunp | grep Hurtworld
(Not all processes could be identified, non-owned process info
 will not be shown, you would have to be root to see it all.)
udp        0      0 0.0.0.0:3565            0.0.0.0:*                           8055/./Hurtworld.x8
udp        0      0 0.0.0.0:12871           0.0.0.0:*                           8055/./Hurtworld.x8
udp        0      0 0.0.0.0:12881           0.0.0.0:*                           8055/./Hurtworld.x8

```

**Comment by UltimateByte** [comment] 2016-05-16 16:16
"@ubuntu-1gb-nyc3-01"
So your CentOS server is called ubuntu ? Or you managed to reinstall it ?

Now you got a decent netstat.
Try to connect again to 104.131.107.91:12871 ?

**Comment by rogerhnn** [comment] 2016-05-16 16:20
Yeah, its called that, don't know why. Every server is called ubuntu in digitalocean.
Tried, no luck.

The server shows on the list, if I try to connect through the list it tries the port 18881 and not 12871.
Manually no luck too. Even using 12871

**Comment by UltimateByte** [comment] 2016-05-16 16:26
Weird. I wish i could try your server, but i don't own the game.
Is there any output in serverfiles/gamelog.txt ?

Can you try to connect to my server ? If mine works, we'll know that it's not a general error.
IP : 164.132.201.49:12871

**Comment by rogerhnn** [comment] 2016-05-16 16:36
I connected to your server, it worked. But mine not.

Here is the output from gamelog.txt
http://pastie.org/10839546

**Comment by UltimateByte** [comment] 2016-05-16 16:38
Server failed to start: Exception0: Failed to bind to port range 12881-12881 ---> System.Net.Sockets.SocketException: Address already in use

Something is using that port already on your machine.
netstat -tulpn | grep :12881

**Comment by rogerhnn** [comment] 2016-05-16 16:40
Weird...

```
[hwserver@ubuntu-1gb-nyc3-01 ~]$ netstat -tulpn | grep :12881
(Not all processes could be identified, non-owned process info
 will not be shown, you would have to be root to see it all.)
udp        0      0 0.0.0.0:12881           0.0.0.0:*                           8551/./Hurtworld.x8

```

**Comment by UltimateByte** [comment] 2016-05-16 16:41
Try the same as root.

**Comment by UltimateByte** [comment] 2016-05-16 16:43
Maybe to isolate issues, you can try to shutdown your hurtworld server first.

**Comment by rogerhnn** [comment] 2016-05-16 16:57
Now it shows nothing...

The server I connected you installed on ubuntu?

**Comment by UltimateByte** [comment] 2016-05-16 16:58
Weird.
It's Debian 8.4 x64
Maybe try an OS reinstall if you got nothing on this machine.
If it still doesn't work, then see with your provider. If you don't have a dedicated IP, that could explain the thing.

**Comment by rogerhnn** [comment] 2016-05-16 17:57
So, installed Ubuntu 14.04 x64...
Installed the scripts...
Voilá... It worked.

Who knows why with the other its not working.

Again, thank you so much for the help UltimateByte :D

**Comment by UltimateByte** [comment] 2016-05-16 18:24
Well, it's often like that with CentOS, that OS isn't appealing to me... Sometimes Ubuntu is kind of a jerk too, too many thing pre-installed and pre-configured weirdly. The safest way to go still seems to be running the latest Debian. Debian, my sweetheart. :o))

**Comment by UltimateByte** [comment] 2016-05-16 18:25
Glad you got it solved though. Closing ;)

**Closed by UltimateByte** 2016-05-16 18:25 UTC
Labels: non-script issue, question
