### ISSUE TITLE
Ark Server Details

### ISSUE THREAD

**Issue by reesey275** [dgibbs64/linuxgsm#844] opened 2016-05-29 00:48 UTC
When running ./arkserver details script it is no longer pulling the IP/Port information from the GameUserSettings.ini file.   This is also creating an issue when stopping the server 
 Stopping ark-server: no queryport found using info_config.sh/home/ark/lgsm/functions/command_stop.sh: line 177: ((: pidcheck <  : syntax error: operand expected (error token is "<  ")

**Comment by UltimateByte** [comment] 2016-05-29 10:15
Did you update your functions ?
`./arkserver uf`

**Comment by reesey275** [comment] 2016-05-29 17:20
Clean installation with new arkserver script.

**Comment by UltimateByte** [comment] 2016-05-29 18:03
I messaged CedarLug about this as he reworked that function recently.

**Comment by cedarlug** [comment] 2016-05-29 19:06
Will check - but I know the current version of the arkserver script lacks an assigned parmslocation, so ./arkserver details won't pull the IP/Port from either location (selfname or GameUserSettings.ini).  See tail comments of #770

**Comment by reesey275** [comment] 2016-05-29 19:11
I had the ports showing correctly in a previous build pulling the info from the GameUserSettings.ini.   HDD failed on that VM so lost quite a bit of the coding that was done to get things to work.

**Comment by cedarlug** [comment] 2016-05-29 19:15
Update:
The original line 177 error in command_stop.sh was a typo that was fixed in the last pull request in the development branch.  The type-o is "MADPIDITER" on line 177 should be "MAXPIDITER", in reference to the maximum number of times the loop checks for an active pid.

**Comment by cedarlug** [comment] 2016-05-29 19:19
@reesey275  Setting in GameUserSettings.ini don't affect the actual runtime assignments.  For example, if you set QueryPort=20735 in GameUserSettings.ini and start the game using ./arkserver start, your service will still be running on port 27015.  

I'd recommend leveraging the the startup parameters in the script (selfname) as the default location, and using GameUserSettings.ini as a backup location for pulling details in the event they are not specified in selfname (arkserver script).

**Comment by reesey275** [comment] 2016-05-29 19:21
I've been using the port setting in GameUserSettings.ini and it works
correctly when launching the server.

**Comment by cedarlug** [comment] 2016-05-29 19:29
Easy enough to verify:
`root@gamerig:~# su - arkserver
arkserver@gamerig:~$ grep QueryPort serverfiles/ShooterGame/Saved/Config/LinuxServer/GameUserSettings.ini 
QueryPort=27025
arkserver@gamerig:~$ grep QueryPort arkserver 
arkserver@gamerig:~$ ./arkserver start
[  OK  ] Starting ark-server: 
arkserver@gamerig:~$ netstat -nap | grep Shoot
(Not all processes could be identified, non-owned process info
 will not be shown, you would have to be root to see it all.)
udp      768      0 0.0.0.0:27015           0.0.0.0:*                           1638/./ShooterGameS `

**Comment by cedarlug** [comment] 2016-05-29 19:36
I'd greatly appreciate someone else's confirmation of the above finding, too.  That setting ports in the GameUserSettings.ini are ignored.  

I'd equally appreciate someone else's counter example as well.

**Comment by reesey275** [comment] 2016-05-29 19:37
You are correct.   Just double checked to make sure.

**Comment by cedarlug** [comment] 2016-05-29 19:40
Thanks for the confirmation.  I'm glad that the type-o is still active, because it led to a better conversation about the correct way to parse parameters.

**Comment by reesey275** [comment] 2016-05-29 19:42
I changed the line from MADIPITER to MAXIPITER and now getting a different error code however.

 

[ WARN ] Stopping ark-server: no queryport found using info_config.sh/home/ark/lgsm/functions/command_stop.sh: line 183: let: -: syntax error: operand expected (error token is "-")

/home/ark/lgsm/functions/command_stop.sh: line 185: [[: -: syntax error: operand expected (error token is "-")

 

Any ideas on this?

**Comment by cedarlug** [comment] 2016-05-29 20:01
can you post (to pastebin) the output of:
`awk 'NR>=162&&NR<=199' ~/lgsm/functions/command_stop.sh`

**Comment by reesey275** [comment] 2016-05-29 20:07
Sure thing. 

[http://pastebin.com/SkhBDLAE](url)

**Comment by cedarlug** [comment] 2016-05-29 20:15
Thanks,

I see what the issue is:  Your port in GameUserSettings.ini isn't the port that the server is actually listening on any more :)   [Because of my request for you to verify that GameUserSettings.ini isn't setting things correctly.]

So, to fix this, make sure that the QueryPort in GameUserSettings.ini matches what you see when you type:
'netstat -nap | grep Shoot'

You'll likely see 3 sockets in-use. The QueryPort is usually in the 27000+ range and UDP.

**Comment by reesey275** [comment] 2016-05-29 20:17
Looks like it's good to go.


 netstat -nap | grep Shoot
(Not all processes could be identified, non-owned process info
 will not be shown, you would have to be root to see it all.)
tcp        0      0 0.0.0.0:32330           0.0.0.0:*               LISTEN      3594/ShooterGameSer
udp        0      0 0.0.0.0:7778            0.0.0.0:*                           3594/ShooterGameSer
udp        0      0 0.0.0.0:27015           0.0.0.0:*                           3594/ShooterGameSer

Thanks for the help.

**Comment by UltimateByte** [comment] 2016-05-30 11:25
@cedarlug @reesey275  So no code issue ? Can we close this ?

**Comment by cedarlug** [comment] 2016-05-30 13:19
This can be closed when #834 is worked into the master branch.  But yes - I believe this can be closed.

**Comment by UltimateByte** [comment] 2016-05-30 13:28
Let's wait for the merge then. ^^

**Closed** 2016-07-12 22:46 UTC
Labels: ark survival evolved
