### ISSUE TITLE
SteamCMD not always detecting updates

### ISSUE THREAD

**Issue by Forge-Media** [dgibbs64/linuxgsm#301] opened 2015-02-27 03:19 UTC
Hi.

Steam just updated my game and I can't connect to my server, I receive the following error:
```Server is running an older version, client version 13473, server version 13472```

I've tried the following command:
```./csgoserver update-restart```

Yet I see the following:
```[  OK  ] Update csgo-server2: Checking for update: SteamCMD
No update available:
        Current version: 531321
        Available version: 531321
        https://steamdb.info/app/740/
[  OK  ] Update csgo-server2: No update available```

However on https://steamdb.info/app/740/history/ I'm seeing the new build: 
```branches/public/buildid: 531321 › 539324```

Is there a delay, before these updates are available?
Thanks

**Comment by Scarsz** [comment] 2015-02-27 09:51
Yeah, it takes a bit before SteamCMD gets updated

**Comment by Forge-Media** [comment] 2015-02-27 19:54
I entered my Steam details into the csgoserver file and managed to update the server to :
```ranches/public/buildid: 531321 › 539324```

However, now there seems to be another one:
```Server is running an older version, client version 13474, server version 13473```

SteamDB:
```branches/public/buildid: 539324 › 539652```

Yet:
```Current version: 539324```
```Available version: 539324```

Really rather annoying

**Comment by dgibbs64** [comment] 2015-02-27 21:23
Its odd as the script gets the version number from steamCMD and compares it to the version number in the app_manifest file so it should just work

**Comment by Forge-Media** [comment] 2015-02-27 22:19
Yeah, it is odd, here is what I'm seeing:
```[csgoserver@vps ~]$ ./csgoserver update-restart
[  OK  ] Update csgo-server: Checking for update: SteamCMD

No update available:
        Current version: 539324
        Available version: 539324
        https://steamdb.info/app/740/

[  OK  ] Update csgo-server: No update available
[csgoserver@vps ~]$
```
Here is the console:
```MasterRequestRestart
Your server needs to be restarted in order to receive the latest update.
L 02/27/2015 - 22:16:42: Your server needs to be restarted in order to receive the latest update.
```

**Comment by dgibbs64** [comment] 2015-02-27 22:38
It just seems that SteamCMD is not picking up the update for some reason and if a restart isnt fixing the issue there is something odd happening. Might be worth running a validate to see if that helps (but create a backup.

**Comment by Forge-Media** [comment] 2015-02-27 23:13
What folder/files will the **./csgoserver backup** function save?

**Comment by Forge-Media** [comment] 2015-02-27 23:43
Did the **./csgoserver validate** function, which successfully updated the server?
Did not appear to overwrite any of my custom files though I did make backups of them
```
./csgoserver validate
loading fn_validate...OK
[ WARN ] Validate csgo-server: Validating may overwrite some customised files.
https://developer.valvesoftware.com/wiki/SteamCMD#Validate

[  OK  ] Validate csgo-server: Checking server filesRedirecting stderr to '/home/csgoserver/Steam/logs/stderr.txt'
[  0%] Checking for available updates...
[----] Verifying installation...
Steam Console Client (c) Valve Corporation
-- type 'quit' to exit --
Loading Steam API...OK.

Logging in user 'fugitive_legacy' to Steam Public...Logged in OK
Waiting for license info...OK
 Update state (0x3) reconfiguring, progress: 0.00 (0 / 0)
 Update state (0x3) reconfiguring, progress: 0.00 (0 / 0)
 Update state (0x3) reconfiguring, progress: 0.00 (0 / 0)
 Update state (0x61) downloading, progress: 6.17 (14660252 / 237558435)
 Update state (0x61) downloading, progress: 34.96 (83043087 / 237558435)
 Update state (0x61) downloading, progress: 99.57 (236528143 / 237558435)
 Update state (0x61) downloading, progress: 100.00 (4283920 / 4283920)
 Update state (0x61) downloading, progress: 100.00 (4283920 / 4283920)
 Update state (0x61) downloading, progress: 100.00 (4283920 / 4283920)
Success! App '740' fully installed.
```
```
[csgoserver@vps ~]$ ./csgoserver update
[  OK  ] Update csgo-server: Checking for update: SteamCMD

No update available:
        Current version: 539652
        Available version: 539652
        https://steamdb.info/app/740/

[  OK  ] Update csgo-server: No update available
```

Thanks for the assistance

**Comment by dgibbs64** [comment] 2015-02-28 15:28
Is the issue resolved? you re opened the issue

**Comment by Forge-Media** [comment] 2015-02-28 20:38
I did not mean to close it just yet, as though **./csgoserver validate** did update the server, I'm still wondering why **./csgoserver update** did not and whether this is a bug?

**Comment by Forge-Media** [comment] 2015-03-01 04:49
Looks like I'm back at square one, https://steamdb.info/app/740/ shows the following version:
**branches/public/buildid: 539652 › 540734**

Trying to update the server shows:
```
No update available:
        Current version: 539652
        Available version: 539652
        https://steamdb.info/app/740/
```

This must be bugged!

**Comment by Forge-Media** [comment] 2015-03-03 20:00
Was hoping to get some clarification regarding the steam_appid.txt file.
I currently have this: **3733 300a 00** should it not be 740 or 730 (740 is server?)

**Comment by Scarsz** [comment] 2015-03-03 20:07
We don't change modify the steam_appid.txt file, steam does. Whatever's in there is what's suppose to be there.

**Comment by Forge-Media** [comment] 2015-03-03 22:11
Well I decided to install a the server locally to see what would be generated as my steam_appid.txt. This was done on windows and the generated steam_appid.txt contains the following text: **730**

 ![steam_appid.txt locally](http://i.imgur.com/jPnzd2d.png)

Certainly find it odd that one server's steam_appid.txt contains what I would expect and another contains a completely random string.

![steam_appid.txt locally](http://i.imgur.com/oyfPevj.png)

I also found this on an older forum post:
![steam_appid.txt locally](http://i.imgur.com/p9Bohv3.png)

For now I'm probably going to wait until another update and attempt the **./csgoserver update-restart** command if this results in the same as above then I will try modifying the steam_appid.txt to see if this affects the result.

**Comment by aN00B1s** [comment] 2015-03-06 04:51
I have the same problem sometimes. On one dedicated server it's working from time to time, on one or second time, on another server it can be not working for a day.
I have not idea why you are speaking about SteamCMD is not picking up the update.
It is fn_update_check - just check function where it's doing wget and it doesn't see new version for some reason.
Maybe some cache problem? Still can't understand. Only way to fix this is to force fn_update_dl .
So problem is in update check.

**Comment by dgibbs64** [comment] 2015-03-06 07:50
The problem is that SteamCMD is still giving the same buildid as whats in the appid file. fn_update_check simply compares the buildid of appmanifest_740.acf with the available release of appid 740 on SteamCMD if they are different an update is started. Might be something to do with caching on SteamCMD but i doubt it. I will be investigating this issue however.

**Comment by aN00B1s** [comment] 2015-03-10 22:28
So if steamCMD is bugged can you just change checks for server update from SteamDB.info?

**Comment by dgibbs64** [comment] 2015-03-11 23:43
Steamdb.info no longer works. They have disabled there api as they didn't intend for it to be used. I will be removing the code soon. I may change the checker to check steamcmd and the log files rather than just one as a fallback

**Comment by aN00B1s** [comment] 2015-03-12 00:08
https://steamdb.info/api/GetRawDepots/?appid=740
I still can check buildid here.

**Comment by spyeagle** [comment] 2015-03-19 01:20
Looks like steamcmd is caching this info.  To fix I went to the Steam folder and renamed the appcache folder as a test.  This then allowed the update to run.  For my own purposes I have modified the script to now remove this directory automatically so a fresh buildid is retrieved.  Hope this helps anyone else having the issue.

**Comment by dgibbs64** [comment] 2015-03-19 08:23
Can you send the code that you have modified please. This may help me with upcoming improvements to the updater. I have a few ideas that should also help

**Comment by dgibbs64** [comment] 2015-03-21 10:28
I have made a couple of changes to the updater to try and resolve this issue. Please let me know how you get on https://github.com/dgibbs64/linuxgsm/commit/b8312d1160271e4a36a0edada3fa11ba9b5e2cdb

**Comment by dgibbs64** [comment] 2015-03-22 23:12
Merging with #323

**Closed by dgibbs64** 2015-03-22 23:12 UTC
Labels: bug, steamcmd
