### ISSUE TITLE
fn_install_serverfiles: line 38 : ./steamcmd.sh no such file or directory

### ISSUE THREAD

**Issue by UltimateByte** [dgibbs64/linuxgsm#413] opened 2015-06-02 22:43 UTC
Trying to install gmodserver on a fresh Debian 8 over Virtualbox, to work onto my server with MySQL then upload it to the true server...
Here is what i got at install
http://image.noelshack.com/fichiers/2015/23/1433284705-fn-install-serverfiles-error.png

:(

Any idea ?

**Comment by UltimateByte** [comment] 2015-06-03 00:03
Well i tried using my main server on which your script used to work flawlessly.
http://image.noelshack.com/fichiers/2015/23/1433289787-debian-ssh-gmodserver-install.png

It's totally broken :(

**Comment by dgibbs64** [comment] 2015-06-03 06:45
Interesting. I'm not sure what the issue is. I will have to test.

**Comment by smt923** [comment] 2015-06-03 06:58
I've sort of had this on and off, retrying once or twice seems to sometimes fix it, but othertimes it will never work, tried on both Ubuntu 15.04 and 14.10, 15.04 hasn't worked once yet (admittedly haven't tried that many times) and 14.10 took a retry or two and then steamcmd would be found

**Comment by UltimateByte** [comment] 2015-06-03 07:01
http://www.garrysmod.com/2015/06/01/15-06-01/
If it's gmod related...
"Added measures against fake servers."
Are you using any kind of hack for installation ?
Because if i try a manual installation with steamcmd (at least on windows) it tells me that i need to be logged in and to own the game. I have to say i'm quite a bit ignorant about that because i almost always used your scripts (at least since a year and a few months). :p 

I bet on a modification of how SteamCMD works. Otherwise a little update of your script containing some crappy lines :p 

smt923: Which game are you installing ?

**Comment by smt923** [comment] 2015-06-03 07:04
on 15.04 I was trying csgo, on 14.10 it's garry's mod

by fake servers that means specifically ones that were using modules or whatever else to fake player  numbers and have more than one copy of themselves, I don't think the lgsm scripts really modify steamcmd in anyway, just download it and access it, I don't think that'd be related to the gmod thing

**Comment by UltimateByte** [comment] 2015-06-03 07:24
You know "hack" can sometimes mean just "use something a different way that it was intended to"...  But if it doesn't work for CS GO neither with the same error, then it's for sure not related to GMod but more to an update of SteamCMD or of LGSM script.

**Comment by dgibbs64** [comment] 2015-06-03 09:05
./steamcmd.sh is not found. the script is now in the wrong dir when trying to install for some reason. This should be an easy fix when I'm home :-)

**Comment by dgibbs64** [comment] 2015-06-03 16:42
https://github.com/dgibbs64/linuxgsm/commit/02f29925588e092af62cb92ef738be20b3a4dafa

**Comment by smt923** [comment] 2015-06-03 17:42
validating a server gives the same error in another function, I assume it's all part of the same issue just with functions that haven't been updated so hopefully reopening this issue is okay

>[  OK  ] Validate gmod-server: Checking server filesloading fn_check_steamcmd...OK
>loading fn_check_steamuser...OK
>/home/steam/1gmod/functions/fn_validate: line 32: ./steamcmd.sh: No such file or directory

**Comment by dgibbs64** [comment] 2015-06-03 17:44
Good call thanks for spotting this. I will double check

**Comment by dgibbs64** [comment] 2015-06-22 10:02
I think I fixed this can it be confirmed so I can close

**Comment by smt923** [comment] 2015-06-22 12:43
from what I can see it looks good, only tested the things I was having issues with before but I haven't ran into this error once,since then so it seems good

**Comment by dgibbs64** [comment] 2015-06-22 12:48
Awesome. Closing

**Closed by dgibbs64** 2015-06-22 12:48 UTC

**Comment by UltimateByte** [comment] 2015-06-22 13:04
Amazing !!! GG !
