### ISSUE TITLE
Arma 3 mod

### ISSUE THREAD

**Issue by Silente13** [dgibbs64/linuxgsm#783] opened 2016-04-18 17:23 UTC
Hi, I followed the tutorial to install the armA3 server. But now i want add some mod, but when i try to enter in the server, it says me that i need the mod. It's how the server don't read the mod... This is the setting

`ARMA3 Modules
add mods with relative paths:
mods/\@CBA_A3\;
or several mods as:
mods/\@CBA_A3\;mods/\@task_force_radio
and chmod modules directories to 775
mods="@servermod;@life_server;@extDB2
Server-side Mods
servermods="@servermod;@life_server;@extdb2`

**Comment by lnxprof** [comment] 2016-04-19 11:22
@Silente13 : What is "\@servermod;" doing in your list?

Check [this post](http://steamcommunity.com/groups/linuxgsm/discussions/0/371918937277688966/) on troubleshooting Arma3 mod deployment.

**Comment by Silente13** [comment] 2016-04-19 14:59
@lnxprof @servemod are the addons for the server. Anyway i see in the link that you post, but i haven't any solution. I still have @servermod NOT FOUND, same for the others mods...

**Comment by lnxprof** [comment] 2016-04-19 15:40
@Silente13 I don't think you understand the syntax of that line (or I don't).  Do you specifically have a mod "@servermod" found in the directory:
`~/serverfiles/@servermod`
because specifying the servermods parameters line as you've done above:
`servermods="\@servermod;\@life_server;\@extdb2`
would indicate that you have THREE modules that you're trying to load,  located on your filesystem as
`~/serverfiles/@servermod`
`~/serverfiles/@live_server`
`~/serverfiles/@extdb2`
Do those directories exist?

**Comment by Silente13** [comment] 2016-04-19 16:13
@lnxprof serverfiles are the directory where the mod and other files are in. I should try with your syntax?

**Comment by Silente13** [comment] 2016-04-19 16:17
![image](https://cloud.githubusercontent.com/assets/16710418/14646745/f5c2cd22-065a-11e6-9f14-415fa3356749.png)

But this is the result.... Like first...

**Comment by lnxprof** [comment] 2016-05-01 21:56
@Silente13: The directory structure looks correct.  I believe all that you need is to escape your semicolons (in addition to your @):
`mods="\@servermod\;\@life_server\;\@extDB2"`
but I'm not sure if these belong in "mods" or "servermods".

**Comment by igeighty** [comment] 2016-05-21 10:56
@Silente13 @lnxprof 

Firstly thanks to @dgibbs64 for the scripts to setup an Arma3 server, The linux flavor of this server had been a bit of a headache due to ambiguous methods mentioned on the Bohemia forums.

I am running Debian 7 and I wished to have all of my mods contained within a 'mod' folder as per the screenshot below.

![screenshot from 2016-05-21 20 18 32](https://cloud.githubusercontent.com/assets/19503471/15447798/496a9ece-1f91-11e6-866a-a1b8afa9c9d6.png)

This is how I edited @dgibbs64 arma3server script to load my mods. This did take a LOT of trial and error until it finally worked with this syntax.

`mods="mods/@cba_a3;mods/@cup_terrains_core;mods/@cup_terrains_maps;mods/@cup_units;mods/@cup_vehicles;mods/@cup_weapons;mods/@rhsafrf;mods/@rhsusaf;mods/@rhsgref;"`

This will then successfully load the mods into the following parameters line.

`Start parameters:
./arma3server -netlog -ip=192.168.1.118 -port=2302 -cfg=/home/arma3server/serverfiles/cfg/arma3-server.network.cfg -config=/home/arma3server/serverfiles/cfg/arma3-server.server.cfg -mod=mods/@cba_a3;mods/@cup_terrains_core;mods/@cup_terrains_maps;mods/@cup_units;mods/@cup_vehicles;mods/@cup_weapons;mods/@rhsafrf;mods/@rhsusaf;mods/@rhsgref; -servermod= -bepath= -autoinit -loadmissiontomemory`

then in the console, i can see they have loaded correctly.

![screenshot from 2016-05-21 20 46 50](https://cloud.githubusercontent.com/assets/19503471/15447945/4c82c862-1f95-11e6-8983-e24d73272a17.png)

hopefully this will help, or to anyone else trying to setup the `mods=` line in Daniels script.

regards./

**Comment by UltimateByte** [comment] 2016-06-13 22:05
Kinda duplicate of this one 
https://github.com/dgibbs64/linuxgsm/issues/651
We might need to change some comments. Please, you guyz, Arma 3 users, make suggestions !

**Closed by UltimateByte** 2016-06-13 22:05 UTC
Labels: arma 3, question

**Comment by numpty9989** [comment] 2017-09-04 18:56
i have tried all mentioned commands and mods are showing in RPT but not in launcher plz help

**Comment by MarkL4YG** [comment] 2017-09-06 06:42
So... yeah this is what we use and it works just fine:
``servermods="mods/@extDB2\;mods/@life_server\;mods/@obfusqf"``
